[firebase]
type = "service_account"
project_id = "ideaism-blog"
private_key_id = "f03ffb0eb89a99cc50cc0645915e10ab175e8377"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8VM1ibTVeOzGR
2b8KW+v96/DXDbP5JmZLEnqKjFxwCiaW+YTnEYJZ8WdErdnrzdXBKqgHZ/j3Fo+Z
+YKbFFTQdVT6OMyFjrNSPmle2Xkhd8mV1mhGTvE0ytZrwpzDDEQA44Z+QVisP9Wv
33DCkPPNLzKqSCGSq6mgXWjqds55uy1TRb8zLI/QzriDii71TR1seSOuLCxwd2mE
j/fq8TaK8PxyVW0EWp/X0FjkYfqiFUgDMCKCfBW5eNZDGIcZT6KTfAwwzhwVPh/u
XbIopQzIj5GacFBndFToRmUkRkVpzK2hI1eTcSKiSXlSWioBgFBgQHnMBDAA62r0
n9ZXy459AgMBAAECggEAUHsy6/F8gYDtTYVOgRhIMNJvsQ8/jmUNCN7kNCoIZK7J
z/HgjDhsypABkBV1T7I+OxbGCKgzejAPfP7mA+y70/uYLXgxWo/hbO+T6v8npxhA
MsKV/BnHNUbLO/DGOgoXU4Pn2TOGt9FtuYNUdikortIRJji99CZczlWsvKm50cXh
70FvtQFEDb5dYv9o34CrABRYvkjALthW08C6njTWPEmVCDHextP4MzmyO1RYRSQ8
cODfsN3jPHQ34qStJv+Upo5sU27YRKdOyjTZ9SHeB03sshO4bGD4BjM8Abdt+h3j
fxFYERkDUJudnN0Zfy6Bhv+GxJbMdUXUTh7wT6+ORwKBgQDpvmzWcUsiqCJq3eD2
zPU/zfTXTCvQIpb0JLAgHKf0YcjScTRju8iX383IMr7vlH6vbGAow9/LU7uzlZYp
9zJzHdLCpmohXkVrFEB9Cc3RzaIVU19q8nTe7KB5BYmahIHBlpcnigbbAoY4imxV
T0UF1o8ZcMeiNs7l10tCu1qy8wKBgQDOQ26Ud3Kj4TrVZulm99U9cHQVlmVqkBi9
sfZVv1iWhigJqqGT/zRje+qVuu6sNqhUDQNQWdCdpeqUgQjP6pv9Jv7U+Fjy//3Y
FIytYXXEDZbDQo0ecIBrU/Mo39lsK+kf0JHDI6Afw8l3e+BMnGdMHVaOYi2mQ16p
YFbAsla0zwKBgQC1N/e1whxYgDY+2ErjzT+O+iSLDvkg4tBZ9F/AZbcpVu6ViULu
19XLOa6XOhCiOmSFqOZcdI/7Wa26q4zCeG5apZKTauX5fNchD5B34LP7pwu0sPDX
P6awdpBrg4mNjJH0/sWt1+s8vRZGm7sl4NFIl3JWbQO5lfiOZX5p/EtzVQKBgBjm
uyrhYM24G0o4KmVr9ip8sQcKKSQ8UUBVg8/GUgOaHqtMFkWvwbtg8mkxMC9KSfgb
uhKxRSZDKZbUHSQ8xqhBVPKRKOvtS9ASawljgrwwh8r69d5+5oIOmISOwcj1ZCeb
Hn3YhzROhrwOEH4vQ6lEwXZfE/PGnl8EanTJEv6xAoGBAJzVpP5wBV7Na87Btkte
fkCJnhgym+AC89TgH/Gb89STDPGauxTV9fBwb9DxzNYp4rlJE+F8gh9WcN/AO8wk
hEQQyJ+/ypXq/BrVveCOX3BmBJUjZkRoyFGsVOWaxAC81QZaSNB2VrR3pmTND5QJ
jbpAllgAZVKFJjqVCO+4MoHS
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-zeusk@ideaism-blog.iam.gserviceaccount.com"
client_id = "111195026095062633402"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-zeusk%40ideaism-blog.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
